/* BROTO — o Tradutor de Jargão.
   O coração do produto: pegar empresas que a gente conhece da vida
   e explicar, sem termo de Faria Lima, o que elas são e por que existem.
   "Itaúsa? É o cofre que é dono de um pedaço do Itaú."

   Regra de escrita: se a sua avó não entender, está errado.
   Nada de "player", "guidance", "valuation". Gente falando com gente. */

export type EmpresaBroto = {
  ticker: string        // o código na bolsa (ex.: ABEV3)
  nome: string          // o nome que aparece na vida (ex.: Ambev)
  emoji: string
  setor: string         // em português de gente
  frase: string         // a explicação de UMA linha — o coração
  oQueFaz: string       // 2-3 frases: o que ela faz pra ganhar dinheiro
  vocesUsa: string      // onde você encontra essa empresa no seu dia
  dono: string          // "ser dono disso significa..."
  site: string          // site institucional — pra pessoa ir conferir com os próprios olhos
  grupo: Grupo          // taxonomia normalizada, usada pelos filtros
}

/* O `setor` é escrito em linguagem de gente e por isso é bem variado.
   O `grupo` é a versão normalizada — é ele que alimenta os filtros. */
export const GRUPOS = [
  'Bancos e Seguros',
  'Energia',
  'Saneamento',
  'Varejo e Consumo',
  'Alimentos e Bebidas',
  'Saúde',
  'Educação',
  'Indústria',
  'Construção e Imóveis',
  'Transporte e Logística',
  'Agro',
  'Tecnologia e Telecom',
  'Mineração e Aço',
  'Papel e Embalagem',
  'Serviços',
] as const

export type Grupo = (typeof GRUPOS)[number]

export const EMPRESAS: EmpresaBroto[] = [
  {
    ticker: 'ABEV3',
    nome: 'Ambev',
    emoji: '🍺',
    setor: 'Bebidas',
    frase: 'A dona da Brahma, Skol, Antarctica e do Guaraná. Se tem cerveja gelada no boteco, provavelmente é dela.',
    oQueFaz: 'A Ambev fabrica e vende bebida — cerveja, refrigerante, água, energético. Ela produz, engarrafa e entrega pro Brasil inteiro. Cada lata que sai do bar vira um pouquinho de lucro pra empresa.',
    vocesUsa: 'Toda vez que você toma uma Brahma, uma Skol, um Guaraná Antarctica ou uma Gatorade.',
    dono: 'Você bebeu a cerveja. Ser dono da Ambev é ficar com um pedacinho da fábrica que fez ela.',
    site: 'https://www.ambev.com.br',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'PETR4',
    nome: 'Petrobras',
    emoji: '⛽',
    setor: 'Energia / Combustível',
    frase: 'A empresa que tira petróleo do fundo do mar e transforma na gasolina do seu posto.',
    oQueFaz: 'A Petrobras acha petróleo embaixo do oceano, tira de lá, refina e vende como gasolina, diesel e gás de cozinha. É uma das maiores do Brasil e paga parte do lucro pros donos todo ano.',
    vocesUsa: 'Toda vez que você abastece o carro, acende o fogão a gás ou pega um ônibus (que roda a diesel).',
    dono: 'Ser dono da Petrobras é ter um pedacinho do petróleo brasileiro trabalhando pra você.',
    site: 'https://petrobras.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'VALE3',
    nome: 'Vale',
    emoji: '⛏️',
    setor: 'Mineração',
    frase: 'Tira ferro do chão no Brasil e vende pro mundo inteiro — principalmente pra China, que usa pra fazer aço.',
    oQueFaz: 'A Vale cava minério de ferro do solo brasileiro e exporta em navios gigantes. Esse ferro vira aço lá fora — que vira prédio, carro, ponte. Quando o mundo constrói muito, a Vale ganha muito.',
    vocesUsa: 'Você não compra da Vale direto, mas o aço do seu carro, do seu fogão e do prédio onde você mora começou como ferro que ela tirou do chão.',
    dono: 'Ser dono da Vale é ter um pedaço do subsolo do Brasil sendo vendido pro mundo.',
    site: 'https://vale.com',
    grupo: 'Mineração e Aço',
  },
  {
    ticker: 'ITSA4',
    nome: 'Itaúsa',
    emoji: '🏦',
    setor: 'Banco / Holding',
    frase: 'É o cofre que é dono de um pedaço do Itaú — e também da Duratex, da fábrica de gás Copagaz e de outras.',
    oQueFaz: 'A Itaúsa não faz produto: ela é dona de fatias de várias empresas boas, sendo o Itaú a maior. É como uma cesta: quando as empresas dentro dela ganham dinheiro, ela recebe e repassa pros donos.',
    vocesUsa: 'Toda vez que você usa o Itaú, passa por uma loja com piso da Duratex ou troca o botijão de gás Copagaz.',
    dono: 'Ser dono da Itaúsa é comprar uma cesta pronta de boas empresas de uma vez só.',
    site: 'https://www.itausa.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'BBAS3',
    nome: 'Banco do Brasil',
    emoji: '🟡',
    setor: 'Banco',
    frase: 'O banco mais antigo do país, onde cai o salário de milhões de brasileiros e o crédito do agronegócio.',
    oQueFaz: 'O Banco do Brasil guarda dinheiro, empresta pra pessoas e pro agro, e cobra juros por isso. É o banco do funcionário público e do produtor rural. Dá parte do lucro pros donos várias vezes por ano.',
    vocesUsa: 'Se você já teve conta no BB, pegou empréstimo, ou conhece alguém que recebe salário do governo por lá.',
    dono: 'Ser dono do Banco do Brasil é receber um pedaço dos juros que o banco ganha todo dia.',
    site: 'https://www.bb.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'MGLU3',
    nome: 'Magazine Luiza',
    emoji: '🛒',
    setor: 'Varejo / Loja',
    frase: 'A loja da "Lu" — vende de geladeira a celular, na loja física e pela internet.',
    oQueFaz: 'O Magalu vende produtos: eletrodoméstico, eletrônico, móvel. Compra barato do fabricante e revende com uma margem. Ganha na loja da esquina e no site/app. É varejo puro — vende muito, ganha um pouquinho em cada.',
    vocesUsa: 'Toda vez que você compra uma TV, um celular ou uma geladeira no Magalu, na loja ou no app.',
    dono: 'Ser dono do Magalu é ficar com um pedacinho de cada venda que a loja faz.',
    site: 'https://www.magazineluiza.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'RENT3',
    nome: 'Localiza',
    emoji: '🚗',
    setor: 'Aluguel de carros',
    frase: 'A maior locadora de carros da América Latina — aquela do aeroporto e do "carro por assinatura".',
    oQueFaz: 'A Localiza compra milhares de carros, aluga por dia (viagem, aeroporto) ou por mês (assinatura), e depois revende os usados. Ganha no aluguel e na revenda. Quanto mais gente aluga em vez de comprar, melhor pra ela.',
    vocesUsa: 'Quando você aluga um carro numa viagem, pega um no aeroporto, ou vê alguém com "carro por assinatura".',
    dono: 'Ser dono da Localiza é ter um pedaço de uma frota gigante de carros rodando e rendendo.',
    site: 'https://www.localiza.com',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'WEGE3',
    nome: 'WEG',
    emoji: '⚙️',
    setor: 'Indústria / Motores',
    frase: 'Uma empresa de Santa Catarina que faz motores elétricos vendidos pro mundo todo — e quase ninguém conhece.',
    oQueFaz: 'A WEG fabrica motores, geradores e equipamentos elétricos que fazem fábricas, elevadores e usinas funcionarem. É uma das empresas mais bem tocadas do Brasil e cresce vendendo pro exterior há décadas.',
    vocesUsa: 'Você raramente vê, mas tem motor WEG no elevador do prédio, na esteira do mercado e na fábrica que faz seus produtos.',
    dono: 'Ser dono da WEG é ter um pedaço da engenharia brasileira que dá certo lá fora.',
    site: 'https://www.weg.net',
    grupo: 'Indústria',
  },
  {
    ticker: 'EGIE3',
    nome: 'Engie Brasil',
    emoji: '💡',
    setor: 'Energia elétrica',
    frase: 'Uma das empresas que geram a luz que acende na sua casa — muito por usinas de água e vento.',
    oQueFaz: 'A Engie tem usinas (hidrelétricas, eólicas, solares) que produzem energia e vendem por contratos longos. É um negócio calmo e previsível: as pessoas sempre precisam de luz. Costuma pagar dividendo bom e estável.',
    vocesUsa: 'Toda vez que você acende a luz, liga o chuveiro ou carrega o celular — parte dessa energia pode vir dela.',
    dono: 'Ser dono da Engie é ganhar um pedaço da conta de luz do Brasil, mês após mês.',
    site: 'https://www.engie.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'NTCO3',
    nome: 'Natura',
    emoji: '🌿',
    setor: 'Cosméticos',
    frase: 'A dona da Natura e da Avon — perfume, creme e maquiagem vendidos muito pela consultora do bairro.',
    oQueFaz: 'A Natura cria e vende produtos de beleza, boa parte pela rede de revendedoras (aquela vizinha que traz o catálogo). Também tem loja e site. Ganha em cada perfume, batom e hidratante vendido.',
    vocesUsa: 'Quando você compra um perfume Natura, um creme, ou recebe o catálogo da consultora Avon.',
    dono: 'Ser dono da Natura é ficar com um pedacinho de cada produto de beleza que ela vende.',
    site: 'https://www.natura.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'ITUB4',
    nome: 'Itaú',
    emoji: '🟠',
    setor: 'Banco',
    frase: 'O maior banco privado do Brasil — a agência laranja, o cartão e o app que quase todo mundo já usou.',
    oQueFaz: 'O Itaú guarda o dinheiro de milhões de pessoas, empresta cobrando juros e cobra tarifa por serviço. Ganha na diferença entre o que paga e o que cobra. É gigante e lucra praticamente todo mês.',
    vocesUsa: 'Se você tem conta, cartão, já baixou o app do Itaú ou financiou alguma coisa com eles.',
    dono: 'Ser dono do Itaú é ganhar um pedaço dos juros e tarifas que o maior banco privado do país recebe.',
    site: 'https://www.itau.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'BBDC4',
    nome: 'Bradesco',
    emoji: '🔴',
    setor: 'Banco',
    frase: 'Outro dos bancões — o do prédio-relógio, presente até em cidade pequena onde mais nada chega.',
    oQueFaz: 'O Bradesco faz o que banco faz: conta, empréstimo, cartão e seguro (é dono da Bradesco Seguros). Está em cidade que outros bancos nem visitam. Ganha com juros e com seguro.',
    vocesUsa: 'Se você tem conta no Bradesco, um seguro Bradesco, ou mora numa cidade onde ele é o banco da praça.',
    dono: 'Ser dono do Bradesco é ficar com um pedaço de um dos bancos mais espalhados do Brasil.',
    site: 'https://banco.bradesco',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'LREN3',
    nome: 'Lojas Renner',
    emoji: '👗',
    setor: 'Varejo / Roupa',
    frase: 'A loja de roupa do shopping — onde você compra camisa, calça e ainda parcela no cartão da loja.',
    oQueFaz: 'A Renner vende roupa e acessórios, no shopping e pela internet. Também ganha com o cartão da própria loja (crédito e juros). Compra da confecção e revende com margem.',
    vocesUsa: 'Toda vez que você compra uma roupa na Renner, ou usa o cartão Renner pra parcelar.',
    dono: 'Ser dono da Renner é ficar com um pedacinho de cada roupa vendida no shopping.',
    site: 'https://www.lojasrenner.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'RADL3',
    nome: 'Raia Drogasil',
    emoji: '💊',
    setor: 'Farmácia',
    frase: 'A dona da Droga Raia e da Drogasil — a farmácia da esquina onde você compra remédio e protetor solar.',
    oQueFaz: 'A Raia Drogasil tem milhares de farmácias pelo Brasil. Vende remédio, higiene e beleza. Ganha um pouquinho em cada caixa e muito no volume — gente sempre precisa de remédio.',
    vocesUsa: 'Toda vez que você compra remédio, shampoo ou vitamina numa Droga Raia ou Drogasil.',
    dono: 'Ser dono da Raia Drogasil é ter um pedaço da farmácia onde o Brasil compra remédio.',
    site: 'https://www.rd.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'VIVT3',
    nome: 'Vivo',
    emoji: '📱',
    setor: 'Telefone / Internet',
    frase: 'A operadora do seu celular e da sua internet — a maior de telefonia do país.',
    oQueFaz: 'A Vivo vende plano de celular, internet e TV. Você paga todo mês, chova ou faça sol. É um negócio de receita que se repete: milhões de contas caindo automático. Costuma pagar bom dividendo.',
    vocesUsa: 'Se o seu chip, sua internet de casa ou sua TV é Vivo — e você paga aquela conta todo mês.',
    dono: 'Ser dono da Vivo é receber um pedaço das contas de celular que o Brasil paga todo mês.',
    site: 'https://www.vivo.com.br',
    grupo: 'Tecnologia e Telecom',
  },
  {
    ticker: 'JBSS3',
    nome: 'JBS',
    emoji: '🥩',
    setor: 'Alimentos / Carne',
    frase: 'A maior empresa de carne do mundo — dona da Friboi, da Seara e de marcas que você come sem saber.',
    oQueFaz: 'A JBS cria, abate e vende carne (boi, frango, porco) pro Brasil e pro mundo. É a maior do planeta no ramo. Ganha vendendo proteína em escala gigante, muito pra exportação.',
    vocesUsa: 'Quando você come um hambúrguer, uma linguiça Seara, ou carne com o selo Friboi.',
    dono: 'Ser dono da JBS é ter um pedaço da maior fábrica de carne do mundo — que é brasileira.',
    site: 'https://jbs.com.br',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'BRFS3',
    nome: 'BRF',
    emoji: '🍗',
    setor: 'Alimentos',
    frase: 'A dona da Sadia e da Perdigão — o frango, a linguiça e o peru de Natal da sua casa.',
    oQueFaz: 'A BRF faz alimento congelado e processado: frango, presunto, nuggets, aquele peru da ceia. Vende no mercado e exporta muito pro Oriente Médio. Ganha no volume de comida do dia a dia.',
    vocesUsa: 'Toda vez que você fritou um nugget Sadia, comeu presunto Perdigão ou assou o peru de Natal.',
    dono: 'Ser dono da BRF é ficar com um pedaço da Sadia e da Perdigão que estão na sua geladeira.',
    site: 'https://www.brf-global.com',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'EMBR3',
    nome: 'Embraer',
    emoji: '✈️',
    setor: 'Indústria / Aviação',
    frase: 'A empresa brasileira que faz avião de verdade — vendido pra companhia aérea do mundo inteiro.',
    oQueFaz: 'A Embraer projeta e fabrica aviões (comerciais, executivos, militares) aqui no Brasil e vende lá fora. É orgulho da engenharia nacional. Ganha em cada avião — que custa uma fortuna.',
    vocesUsa: 'Provavelmente você já voou num avião da Embraer sem saber — muita ponte-aérea usa os jatos dela.',
    dono: 'Ser dono da Embraer é ter um pedaço da empresa que fez o Brasil construir avião.',
    site: 'https://embraer.com',
    grupo: 'Indústria',
  },
  {
    ticker: 'SUZB3',
    nome: 'Suzano',
    emoji: '📄',
    setor: 'Papel e Celulose',
    frase: 'A maior fabricante de papel do mundo — o papel higiênico e a folha do caderno começam nela.',
    oQueFaz: 'A Suzano planta eucalipto, transforma em celulose e vende pro mundo fazer papel. É a número 1 do planeta nisso. Ganha exportando celulose, boa parte em dólar.',
    vocesUsa: 'O papel higiênico, o guardanapo e a folha do seu caderno provavelmente vieram de árvore da Suzano.',
    dono: 'Ser dono da Suzano é ter um pedaço das florestas de eucalipto que viram papel no mundo todo.',
    site: 'https://www.suzano.com.br',
    grupo: 'Papel e Embalagem',
  },
  {
    ticker: 'GGBR4',
    nome: 'Gerdau',
    emoji: '🏗️',
    setor: 'Aço / Construção',
    frase: 'A empresa do vergalhão — aquele ferro que segura a laje da casa que o brasileiro constrói.',
    oQueFaz: 'A Gerdau faz aço: vergalhão, viga, prego. Recicla sucata e transforma em ferro pra construção. Quando o Brasil constrói casa e obra, a Gerdau vende mais.',
    vocesUsa: 'Se a sua casa (ou a laje do vizinho) tem vergalhão, tem boa chance de ser aço Gerdau.',
    dono: 'Ser dono da Gerdau é ter um pedaço do aço que levanta as casas do Brasil.',
    site: 'https://www.gerdau.com.br',
    grupo: 'Mineração e Aço',
  },
  {
    ticker: 'ELET3',
    nome: 'Eletrobras',
    emoji: '⚡',
    setor: 'Energia elétrica',
    frase: 'A maior empresa de energia da América Latina — com usinas gigantes como parte de Itaipu e Furnas.',
    oQueFaz: 'A Eletrobras gera e transmite energia em escala nacional: usinas enormes e as linhas que levam luz de um canto a outro do país. Vende energia por contratos longos.',
    vocesUsa: 'Parte da luz que chega na sua casa passou pelas linhas e usinas da Eletrobras.',
    dono: 'Ser dono da Eletrobras é ter um pedaço da espinha dorsal de energia do Brasil.',
    site: 'https://www.eletrobras.com',
    grupo: 'Energia',
  },
  {
    ticker: 'SBSP3',
    nome: 'Sabesp',
    emoji: '💧',
    setor: 'Água e Saneamento',
    frase: 'A empresa que leva água tratada e esgoto pra maior parte de São Paulo — a conta de água do paulista.',
    oQueFaz: 'A Sabesp capta, trata e distribui água, e cuida do esgoto de São Paulo. Você paga a conta todo mês. É serviço essencial e previsível: ninguém deixa de usar água.',
    vocesUsa: 'Se você mora em São Paulo e abre a torneira ou dá descarga — é Sabesp por trás.',
    dono: 'Ser dono da Sabesp é receber um pedaço da conta de água de milhões de paulistas.',
    site: 'https://www.sabesp.com.br',
    grupo: 'Saneamento',
  },
  {
    ticker: 'ASAI3',
    nome: 'Assaí',
    emoji: '🏷️',
    setor: 'Atacarejo',
    frase: 'O atacarejo onde a família compra o mês inteiro e o dono do bar abastece o negócio.',
    oQueFaz: 'O Assaí vende comida e produto de casa em grande quantidade, com preço de atacado, pra pessoa física e pequeno comércio. Ganha em volume gigante com margem apertada.',
    vocesUsa: 'Quando você faz a compra grande do mês no Assaí, ou vê o dono da lanchonete abastecendo por lá.',
    dono: 'Ser dono do Assaí é ficar com um pedacinho da compra do mês de milhões de famílias.',
    site: 'https://www.assai.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'CRFB3',
    nome: 'Carrefour',
    emoji: '🏬',
    setor: 'Supermercado',
    frase: 'A rede de supermercado e atacarejo (o Atacadão) onde metade do Brasil faz mercado.',
    oQueFaz: 'O Carrefour tem supermercado, hipermercado e o Atacadão. Vende comida, eletrônico, de tudo. Ainda tem banco próprio (o cartão Carrefour). Ganha em volume enorme.',
    vocesUsa: 'Toda vez que você faz mercado no Carrefour ou no Atacadão, ou passa o cartão da loja.',
    dono: 'Ser dono do Carrefour é ter um pedaço de onde o Brasil enche o carrinho toda semana.',
    site: 'https://www.carrefour.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'UGPA3',
    nome: 'Ultrapar',
    emoji: '🛢️',
    setor: 'Combustível e Gás',
    frase: '"Pergunta pro posto Ipiranga" — é ela a dona. E também do gás Ultragaz do seu fogão.',
    oQueFaz: 'A Ultrapar é dona dos postos Ipiranga e da Ultragaz (o botijão). Distribui combustível e gás pro Brasil todo. Ganha em cada litro abastecido e cada botijão trocado.',
    vocesUsa: 'Quando você abastece num posto Ipiranga ou troca o botijão de gás Ultragaz.',
    dono: 'Ser dono da Ultrapar é ficar com um pedaço de cada tanque cheio no Ipiranga.',
    site: 'https://www.ultra.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'TIMS3',
    nome: 'TIM',
    emoji: '📶',
    setor: 'Telefone / Internet',
    frase: 'Uma das operadoras do seu celular — o chip, os dados e a ligação de milhões de brasileiros.',
    oQueFaz: 'A TIM vende plano de celular e internet móvel. Milhões de pessoas pagam todo mês pelo sinal. É receita que se repete e não depende de a pessoa "querer comprar" — ela precisa do telefone.',
    vocesUsa: 'Se o seu chip é TIM, ou a internet do seu celular vem dela.',
    dono: 'Ser dono da TIM é receber um pedaço das recargas e planos que o Brasil paga todo mês.',
    site: 'https://www.tim.com.br',
    grupo: 'Tecnologia e Telecom',
  },
  {
    ticker: 'CMIG4',
    nome: 'Cemig',
    emoji: '🔌',
    setor: 'Energia elétrica',
    frase: 'A empresa que leva luz pra maior parte de Minas Gerais — a conta de energia do mineiro.',
    oQueFaz: 'A Cemig gera e distribui energia elétrica em Minas. Você paga a conta de luz todo mês. É serviço essencial e regulado, e costuma pagar bom dividendo.',
    vocesUsa: 'Se você mora em Minas e acende a luz, é Cemig na conta.',
    dono: 'Ser dono da Cemig é receber um pedaço da conta de luz de Minas Gerais.',
    site: 'https://www.cemig.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'PETZ3',
    nome: 'Petz',
    emoji: '🐶',
    setor: 'Varejo / Pet',
    frase: 'A maior rede de pet shop do Brasil — ração, banho e tosa pro seu bicho.',
    oQueFaz: 'A Petz vende tudo pra animal de estimação: ração, remédio, brinquedo, e ainda banho, tosa e veterinário. Ganha com o gasto que a gente faz com cachorro e gato — que só cresce.',
    vocesUsa: 'Toda vez que você compra ração, leva o pet pro banho ou no veterinário da Petz.',
    dono: 'Ser dono da Petz é ficar com um pedacinho do que o Brasil gasta com os bichos.',
    site: 'https://www.petz.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'CVCB3',
    nome: 'CVC',
    emoji: '🧳',
    setor: 'Viagem / Turismo',
    frase: 'A maior agência de viagem do Brasil — o pacote de férias, a lua de mel, aquela viagem parcelada.',
    oQueFaz: 'A CVC vende pacote de viagem: passagem, hotel e passeio, tudo junto e parcelado. Ganha uma comissão em cada viagem vendida. Quando o brasileiro viaja mais, ela ganha mais.',
    vocesUsa: 'Se você já comprou um pacote de viagem ou parcelou umas férias na CVC.',
    dono: 'Ser dono da CVC é ficar com um pedaço das viagens que o Brasil parcela pra realizar.',
    site: 'https://www.cvc.com.br',
    grupo: 'Serviços',
  },
  {
    ticker: 'AZUL4',
    nome: 'Azul',
    emoji: '🛫',
    setor: 'Aviação',
    frase: 'A companhia aérea das poltronas azuis — leva você (e muita cidade pequena) pra voar.',
    oQueFaz: 'A Azul transporta gente de avião pelo Brasil, chegando em cidades onde outras não vão. Ganha vendendo passagem. É um negócio difícil (combustível, dólar), mas de marca muito conhecida.',
    vocesUsa: 'Toda vez que você voa de Azul, ou pega um voo naqueles aeroportos menores.',
    dono: 'Ser dono da Azul é ter um pedaço de uma das companhias que colocam o Brasil no ar.',
    site: 'https://www.voeazul.com.br',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'MRFG3',
    nome: 'Marfrig',
    emoji: '🍔',
    setor: 'Alimentos / Carne',
    frase: 'Uma das gigantes da carne — faz o hambúrguer de rede famosa que você come sem saber.',
    oQueFaz: 'A Marfrig produz carne bovina e é uma das maiores fabricantes de hambúrguer do mundo — fornece pra grandes redes de fast-food. Ganha vendendo proteína em escala, muito pra fora.',
    vocesUsa: 'Aquele hambúrguer da rede famosa? Tem boa chance de a carne ter saído da Marfrig.',
    dono: 'Ser dono da Marfrig é ter um pedaço da carne que vira hambúrguer no mundo todo.',
    site: 'https://www.marfrig.com.br',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'HAPV3',
    nome: 'Hapvida',
    emoji: '🏥',
    setor: 'Saúde / Plano',
    frase: 'Um dos maiores planos de saúde do Brasil — o convênio médico de milhões de famílias.',
    oQueFaz: 'A Hapvida vende plano de saúde e tem hospitais e clínicas próprios. Você paga a mensalidade e usa quando precisa. Ganha na diferença entre o que recebe e o que gasta com atendimento.',
    vocesUsa: 'Se você ou alguém da família tem plano Hapvida (ou NotreDame Intermédica).',
    dono: 'Ser dono da Hapvida é ter um pedaço do convênio médico de milhões de brasileiros.',
    site: 'https://www.hapvida.com.br',
    grupo: 'Saúde',
  },
  {
    ticker: 'RAIZ4',
    nome: 'Raízen',
    emoji: '🐚',
    setor: 'Combustível / Etanol',
    frase: 'A dona dos postos Shell no Brasil — e uma das maiores fabricantes de etanol de cana do mundo.',
    oQueFaz: 'A Raízen distribui combustível nos postos Shell e produz açúcar e etanol a partir da cana. Ganha no combustível vendido e no etanol. É uma sociedade da Cosan com a Shell.',
    vocesUsa: 'Toda vez que você abastece num posto Shell, ou coloca etanol no carro.',
    dono: 'Ser dono da Raízen é ficar com um pedaço de cada litro abastecido no posto Shell.',
    site: 'https://www.raizen.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'FLRY3',
    nome: 'Fleury',
    emoji: '🩺',
    setor: 'Saúde / Laboratório',
    frase: 'A rede de laboratório onde você faz exame de sangue e check-up — o resultado que o médico pede.',
    oQueFaz: 'O Fleury faz exames: sangue, imagem, check-up. Você (ou seu plano) paga por cada exame. É saúde, que sempre tem demanda. Marca conhecida por qualidade nas grandes cidades.',
    vocesUsa: 'Quando o médico pede um exame e você faz no Fleury (ou num laboratório do grupo).',
    dono: 'Ser dono do Fleury é ficar com um pedaço de cada exame que o Brasil faz pra se cuidar.',
    site: 'https://www.fleury.com.br',
    grupo: 'Saúde',
  },
  {
    ticker: 'KLBN11',
    nome: 'Klabin',
    emoji: '📦',
    setor: 'Papel e Embalagem',
    frase: 'A empresa da caixa de papelão — aquela do seu delivery e da embalagem do mercado.',
    oQueFaz: 'A Klabin faz papel e papelão pra embalagem: a caixa da compra online, o saco de cimento, a embalagem de alimento. Planta a árvore, faz o papel e vende. Quanto mais o país entrega, mais ela vende.',
    vocesUsa: 'Toda caixa de papelão que chega na sua porta pode ter começado na Klabin.',
    dono: 'Ser dono da Klabin é ter um pedaço de cada caixa de papelão que roda no Brasil.',
    site: 'https://www.klabin.com.br',
    grupo: 'Papel e Embalagem',
  },
  {
    ticker: 'B3SA3',
    nome: 'B3',
    emoji: '🏛️',
    setor: 'Bolsa de Valores',
    frase: 'A dona da própria bolsa — o lugar onde todas essas ações são compradas e vendidas.',
    oQueFaz: 'A B3 é a bolsa brasileira. Ela não compra ação: ela é o mercado onde todo mundo negocia, e cobra uma taxinha em cada negócio feito. Ganha com o movimento — não com o preço subir ou cair.',
    vocesUsa: 'Toda vez que alguém no Brasil compra ou vende uma ação. Inclusive você, se investir.',
    dono: 'Ser dono da B3 é ficar com um pedaço da taxa de cada negócio feito na bolsa brasileira.',
    site: 'https://www.b3.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'SANB11',
    nome: 'Santander',
    emoji: '🔺',
    setor: 'Banco',
    frase: 'O banco vermelho de origem espanhola — um dos maiores do Brasil.',
    oQueFaz: 'O Santander faz conta, cartão, empréstimo e financiamento. Ganha com juros e tarifas, como todo banco. É forte em financiamento de carro e crédito pra empresa.',
    vocesUsa: 'Se você tem conta, cartão ou financiou um carro no Santander.',
    dono: 'Ser dono do Santander é receber um pedaço dos juros de um dos maiores bancos do país.',
    site: 'https://www.santander.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'BPAC11',
    nome: 'BTG Pactual',
    emoji: '💼',
    setor: 'Banco de Investimento',
    frase: 'O maior banco de investimento da América Latina — o banco dos ricos que virou app de gente comum.',
    oQueFaz: 'O BTG cuida de grandes fortunas, assessora empresas em negócios bilionários e hoje também tem banco digital pra pessoa física. Ganha com taxa de gestão, comissão e juros.',
    vocesUsa: 'Se você usa o app do BTG ou investe por lá.',
    dono: 'Ser dono do BTG é ter um pedaço do banco que cuida do dinheiro dos muito ricos.',
    site: 'https://www.btgpactual.com',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'ALPA4',
    nome: 'Alpargatas',
    emoji: '🩴',
    setor: 'Calçados',
    frase: 'A dona das Havaianas — o chinelo brasileiro que o mundo inteiro calça.',
    oQueFaz: 'A Alpargatas fabrica e vende Havaianas (e a Osklen). Vende chinelo no Brasil e exporta pra mais de 100 países. Ganha em cada par vendido — e são centenas de milhões por ano.',
    vocesUsa: 'Todo par de Havaianas que você já calçou na vida.',
    dono: 'Ser dono da Alpargatas é ter um pedaço do chinelo mais brasileiro que existe.',
    site: 'https://www.alpargatas.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'SMFT3',
    nome: 'Smart Fit',
    emoji: '💪',
    setor: 'Academia',
    frase: 'A maior rede de academia da América Latina — aquela mensalidade baratinha do bairro.',
    oQueFaz: 'A Smart Fit tem academias de preço acessível espalhadas pelo Brasil e pela América Latina. Você paga a mensalidade todo mês, indo ou não. Ganha com um volume enorme de alunos.',
    vocesUsa: 'Se você treina (ou já pagou sem ir) numa Smart Fit.',
    dono: 'Ser dono da Smart Fit é receber um pedaço da mensalidade de milhões de alunos.',
    site: 'https://www.smartfit.com.br',
    grupo: 'Serviços',
  },
  {
    ticker: 'VIVA3',
    nome: 'Vivara',
    emoji: '💍',
    setor: 'Joias',
    frase: 'A maior joalheria do Brasil — a aliança, o presente de Dia das Mães, o berloque Life.',
    oQueFaz: 'A Vivara cria e vende joias e relógios, em lojas de shopping e online. Fabrica boa parte no Brasil. Ganha com margem alta — joia é produto de desejo, não de necessidade.',
    vocesUsa: 'Quando você compra (ou ganha) uma joia, um berloque Life ou uma aliança da Vivara.',
    dono: 'Ser dono da Vivara é ficar com um pedaço de cada joia que o Brasil dá de presente.',
    site: 'https://www.vivara.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'AZZA3',
    nome: 'Azzas 2154',
    emoji: '👠',
    setor: 'Moda e Calçado',
    frase: 'A dona da Arezzo, da Schutz e da Farm — o sapato e a roupa que dominam o shopping.',
    oQueFaz: 'A Azzas nasceu da união da Arezzo com o Grupo Soma. Cria e vende calçado e moda de marcas fortes. Ganha em cada peça vendida, com margem boa por serem marcas desejadas.',
    vocesUsa: 'Se você tem um sapato Arezzo, um Schutz, ou uma roupa da Farm.',
    dono: 'Ser dono da Azzas é ter um pedaço das marcas de moda que o Brasil quer usar.',
    site: 'https://www.azzas2154.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'MRVE3',
    nome: 'MRV',
    emoji: '🏘️',
    setor: 'Construção / Casa popular',
    frase: 'A construtora do Minha Casa Minha Vida — faz o apartamento onde muita família começa.',
    oQueFaz: 'A MRV constrói e vende apartamento de baixa e média renda, muito ligado ao financiamento habitacional. Ganha na venda de cada unidade. Quando há crédito pra casa própria, ela cresce.',
    vocesUsa: 'Se você, um parente ou um amigo comprou apartamento pelo Minha Casa Minha Vida.',
    dono: 'Ser dono da MRV é ter um pedaço das casas que o Brasil constrói pra quem está começando.',
    site: 'https://www.mrv.com.br',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'CYRE3',
    nome: 'Cyrela',
    emoji: '🏢',
    setor: 'Construção / Alto padrão',
    frase: 'A construtora dos prédios de alto padrão — aquele empreendimento chique da avenida.',
    oQueFaz: 'A Cyrela incorpora e constrói prédios residenciais para média e alta renda. Compra o terreno, lança o empreendimento e vende as unidades. Ganha na margem de cada torre vendida.',
    vocesUsa: 'Aquele prédio novo e caro que subiu no seu bairro pode ser Cyrela.',
    dono: 'Ser dono da Cyrela é ter um pedaço dos prédios que mudam a paisagem da cidade.',
    site: 'https://www.cyrela.com.br',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'TAEE11',
    nome: 'Taesa',
    emoji: '🗼',
    setor: 'Transmissão de energia',
    frase: 'A dona das torres e linhões que levam energia de uma ponta a outra do país.',
    oQueFaz: 'A Taesa não gera energia: ela transporta. É dona de linhas de transmissão e recebe um valor fixo por manter tudo funcionando. Receita muito previsível — por isso é famosa por pagar dividendo.',
    vocesUsa: 'Aqueles linhões gigantes que você vê na estrada levando energia.',
    dono: 'Ser dono da Taesa é receber um pedaço do pedágio da energia que atravessa o Brasil.',
    site: 'https://www.taesa.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'RAIL3',
    nome: 'Rumo',
    emoji: '🚂',
    setor: 'Ferrovia / Logística',
    frase: 'A maior empresa de ferrovia do Brasil — leva a soja da fazenda até o porto.',
    oQueFaz: 'A Rumo opera trens de carga, levando grão, açúcar e combustível do interior pros portos. Cobra pelo transporte. Quanto mais o agro produz e exporta, mais trem ela roda.',
    vocesUsa: 'Você não anda nela, mas a comida que o Brasil exporta anda — e isso segura a economia.',
    dono: 'Ser dono da Rumo é ter um pedaço dos trilhos que escoam a safra brasileira.',
    site: 'https://www.rumolog.com',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'POMO4',
    nome: 'Marcopolo',
    emoji: '🚌',
    setor: 'Indústria / Ônibus',
    frase: 'A empresa que faz a carroceria do ônibus — provavelmente o que você pega todo dia.',
    oQueFaz: 'A Marcopolo fabrica carroceria de ônibus (urbano, rodoviário, escolar) no Brasil e exporta pro mundo. Ganha em cada ônibus produzido. Quando cidade e viação renovam frota, ela vende.',
    vocesUsa: 'É bem provável que o ônibus que você pega pro trabalho tenha carroceria Marcopolo.',
    dono: 'Ser dono da Marcopolo é ter um pedaço dos ônibus que carregam o Brasil todo dia.',
    site: 'https://www.marcopolo.com.br',
    grupo: 'Indústria',
  },
  {
    ticker: 'USIM5',
    nome: 'Usiminas',
    emoji: '🔩',
    setor: 'Aço / Indústria',
    frase: 'A siderúrgica das chapas de aço — a lataria do seu carro e a porta da sua geladeira.',
    oQueFaz: 'A Usiminas transforma minério em chapa de aço plana, usada pela indústria de carro e de eletrodoméstico. Ganha vendendo aço pra fábrica. Depende muito de a indústria estar aquecida.',
    vocesUsa: 'A lataria do seu carro, a porta da geladeira e o fogão têm aço desse tipo.',
    dono: 'Ser dono da Usiminas é ter um pedaço do aço que vira carro e geladeira.',
    site: 'https://www.usiminas.com',
    grupo: 'Mineração e Aço',
  },
  {
    ticker: 'SLCE3',
    nome: 'SLC Agrícola',
    emoji: '🌾',
    setor: 'Agronegócio',
    frase: 'Uma das maiores fazendas do Brasil, listada na bolsa — planta soja, milho e algodão.',
    oQueFaz: 'A SLC é dona de fazendas gigantes e planta grão em escala industrial. Vende a safra, muito pra exportação em dólar. É agro de verdade, com terra e trator, virando ação.',
    vocesUsa: 'A soja e o algodão que viram ração, óleo de cozinha e a roupa que você veste.',
    dono: 'Ser dono da SLC é ser, literalmente, dono de um pedaço de fazenda brasileira.',
    site: 'https://www.slcagricola.com.br',
    grupo: 'Agro',
  },
  {
    ticker: 'TOTS3',
    nome: 'Totvs',
    emoji: '💻',
    setor: 'Software',
    frase: 'O software que faz a empresa funcionar por dentro — a nota fiscal, o estoque, a folha.',
    oQueFaz: 'A Totvs vende sistema de gestão pra empresa brasileira: controla estoque, venda, imposto e funcionário. Cobra assinatura mensal. Depois de instalado, a empresa dificilmente troca.',
    vocesUsa: 'A nota fiscal que você recebe na loja provavelmente saiu de um sistema Totvs.',
    dono: 'Ser dono da Totvs é receber um pedaço da mensalidade que milhares de empresas pagam.',
    site: 'https://www.totvs.com',
    grupo: 'Tecnologia e Telecom',
  },
  {
    ticker: 'LWSA3',
    nome: 'Locaweb',
    emoji: '🌐',
    setor: 'Internet / Tecnologia',
    frase: 'A empresa que hospeda site e loja virtual — a estrutura de quem vende pela internet.',
    oQueFaz: 'A Locaweb oferece hospedagem, e-mail profissional e plataforma de loja virtual pra pequeno e médio negócio. Cobra assinatura. Ganha quando mais gente empreende online.',
    vocesUsa: 'Aquela lojinha online onde você comprou pode estar rodando na Locaweb.',
    dono: 'Ser dono da Locaweb é ter um pedaço da estrutura por trás do comércio online brasileiro.',
    site: 'https://www.locaweb.com.br',
    grupo: 'Tecnologia e Telecom',
  },
  {
    ticker: 'YDUQ3',
    nome: 'Yduqs',
    emoji: '🎓',
    setor: 'Educação',
    frase: 'A dona da Estácio — uma das maiores faculdades particulares do país.',
    oQueFaz: 'A Yduqs tem faculdades (Estácio, Ibmec, Idomed), presenciais e a distância. Cobra mensalidade dos alunos. Ganha com volume de matrículas, muito ligado a financiamento estudantil.',
    vocesUsa: 'Se você, ou alguém que você conhece, estudou na Estácio.',
    dono: 'Ser dono da Yduqs é receber um pedaço das mensalidades de quem está se formando.',
    site: 'https://www.yduqs.com.br',
    grupo: 'Educação',
  },
  {
    ticker: 'COGN3',
    nome: 'Cogna',
    emoji: '📚',
    setor: 'Educação',
    frase: 'A dona da Anhanguera e da Kroton — e dos livros didáticos de muita escola.',
    oQueFaz: 'A Cogna atua em ensino superior (Anhanguera, Unopar) e em material didático pra escolas. Vive de mensalidade e de contrato com colégio. É uma das maiores educadoras privadas do país.',
    vocesUsa: 'Se você estudou na Anhanguera ou na Unopar, ou usou apostila de escola do grupo.',
    dono: 'Ser dono da Cogna é ter um pedaço da educação privada em escala no Brasil.',
    site: 'https://www.cogna.com.br',
    grupo: 'Educação',
  },
  {
    ticker: 'ODPV3',
    nome: 'Odontoprev',
    emoji: '🦷',
    setor: 'Saúde / Plano dental',
    frase: 'O maior plano odontológico do Brasil — o convênio do dentista.',
    oQueFaz: 'A Odontoprev vende plano dental, muito por empresas pros funcionários. Você paga uma mensalidade baixa e usa a rede de dentistas. Ganha na diferença entre a mensalidade e o custo do atendimento.',
    vocesUsa: 'Se você tem plano de dentista pelo trabalho, tem boa chance de ser Odontoprev.',
    dono: 'Ser dono da Odontoprev é receber um pedaço do plano de dentista de milhões de pessoas.',
    site: 'https://www.odontoprev.com.br',
    grupo: 'Saúde',
  },
  {
    ticker: 'MULT3',
    nome: 'Multiplan',
    emoji: '🛍️',
    setor: 'Shopping centers',
    frase: 'A dona de shopping — ela não vende na loja, ela é dona do prédio e recebe o aluguel.',
    oQueFaz: 'A Multiplan constrói e administra shoppings (como o MorumbiShopping e o BarraShopping). As lojas pagam aluguel pra ela. Ganha com aluguel e estacionamento — recebe mesmo sem vender nada.',
    vocesUsa: 'Toda vez que você passeia, come na praça de alimentação ou estaciona num shopping do grupo.',
    dono: 'Ser dono da Multiplan é ser dono do shopping, não da loja — você recebe o aluguel.',
    site: 'https://www.multiplan.com.br',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'CSAN3',
    nome: 'Cosan',
    emoji: '🧭',
    setor: 'Energia e Logística',
    frase: 'Um grupo que reúne negócios de combustível, gás, ferrovia e lubrificante.',
    oQueFaz: 'A Cosan é dona de participações em empresas como Raízen, Rumo, Compass e Moove. Em vez de vender uma coisa só, ela ganha quando esses negócios transportam carga, distribuem gás ou vendem energia e combustível.',
    vocesUsa: 'Quando você abastece num posto Shell, vê um trem da Rumo ou usa gás distribuído pela Compass.',
    dono: 'Ser dono da Cosan é ter uma cesta de negócios ligados à energia e à logística.',
    site: 'https://www.cosan.com.br/sobre-a-cosan/',
    grupo: 'Energia',
  },
  {
    ticker: 'EQTL3',
    nome: 'Equatorial Energia',
    emoji: '🔌',
    setor: 'Energia e Saneamento',
    frase: 'Leva energia para milhões de casas e também entrou no negócio de água e esgoto.',
    oQueFaz: 'A Equatorial distribui energia em vários estados, transmite eletricidade e opera serviços de saneamento. A maior parte da receita vem de contas pagas todos os meses por serviços essenciais.',
    vocesUsa: 'Se você mora em estados como Maranhão, Pará, Piauí, Alagoas, Amapá, Goiás ou Rio Grande do Sul, sua conta de luz pode ser dela.',
    dono: 'Ser dono da Equatorial é participar de serviços básicos que precisam funcionar todos os dias.',
    site: 'https://ri.equatorialenergia.com.br/',
    grupo: 'Energia',
  },
  {
    ticker: 'CPFE3',
    nome: 'CPFL Energia',
    emoji: '💡',
    setor: 'Energia elétrica',
    frase: 'Gera e entrega energia para casas e empresas, principalmente no interior de São Paulo e no Sul.',
    oQueFaz: 'A CPFL produz, transmite, distribui e comercializa eletricidade. Como a energia é um serviço essencial, milhões de clientes pagam a conta todos os meses.',
    vocesUsa: 'Se você acende a luz em cidades atendidas pela CPFL Paulista, Piratininga, RGE ou Santa Cruz.',
    dono: 'Ser dono da CPFL é participar de várias etapas do caminho da energia até a tomada.',
    site: 'https://ri.cpfl.com.br/',
    grupo: 'Energia',
  },
  {
    ticker: 'ENEV3',
    nome: 'Eneva',
    emoji: '🔥',
    setor: 'Energia e Gás',
    frase: 'Encontra gás natural e usa esse gás para produzir eletricidade perto de onde ele sai do chão.',
    oQueFaz: 'A Eneva procura e produz gás natural, além de operar usinas que transformam esse gás em energia. Também vende soluções de energia para indústrias.',
    vocesUsa: 'Você não compra dela diretamente, mas a energia que mantém casas e fábricas ligadas pode sair de uma de suas usinas.',
    dono: 'Ser dono da Eneva é participar do caminho que vai do gás natural até a eletricidade.',
    site: 'https://eneva.com.br/quem-somos/',
    grupo: 'Energia',
  },
  {
    ticker: 'PRIO3',
    nome: 'PRIO',
    emoji: '🛢️',
    setor: 'Petróleo',
    frase: 'Compra campos de petróleo maduros e tenta fazê-los produzir mais e gastar menos.',
    oQueFaz: 'A PRIO produz petróleo no mar. Sua especialidade é assumir campos que já existem, melhorar a operação e reduzir o custo de cada barril vendido.',
    vocesUsa: 'Você não vê a marca no posto, mas o petróleo produzido por ela entra na cadeia de combustíveis e outros produtos.',
    dono: 'Ser dono da PRIO é participar de campos de petróleo cujo resultado depende do preço do barril e da eficiência da operação.',
    site: 'https://ri.prio3.com.br/',
    grupo: 'Energia',
  },
  {
    ticker: 'CSNA3',
    nome: 'CSN',
    emoji: '🏭',
    setor: 'Aço, Mineração e Cimento',
    frase: 'Faz aço, tira minério, produz cimento e ainda transporta parte dessa carga.',
    oQueFaz: 'A CSN reúne siderurgia, mineração, cimento, energia e logística. Vende materiais que viram carro, eletrodoméstico, prédio e estrada.',
    vocesUsa: 'A chapa do carro, a lata, o cimento da obra ou o aço de um eletrodoméstico podem ter passado por ela.',
    dono: 'Ser dono da CSN é participar de vários materiais e serviços usados para construir e produzir.',
    site: 'https://www.csn.com.br/quem-somos/',
    grupo: 'Mineração e Aço',
  },
  {
    ticker: 'GOAU4',
    nome: 'Metalúrgica Gerdau',
    emoji: '🔩',
    setor: 'Aço / Holding',
    frase: 'É a empresa que controla uma grande parte da Gerdau, uma das maiores produtoras de aço do país.',
    oQueFaz: 'A Metalúrgica Gerdau é uma holding: seu principal ativo é a participação na Gerdau. Por isso, seu resultado acompanha de perto o negócio de produzir e vender aço no Brasil e no exterior.',
    vocesUsa: 'O vergalhão da obra, a peça de um carro ou o aço reciclado pode vir de uma operação da Gerdau.',
    dono: 'Ser dono da Metalúrgica Gerdau é ter uma participação indireta no negócio de aço da Gerdau.',
    site: 'https://ri.gerdau.com/',
    grupo: 'Mineração e Aço',
  },
  {
    ticker: 'CSMG3',
    nome: 'Copasa',
    emoji: '🚰',
    setor: 'Água e Saneamento',
    frase: 'Trata e distribui água, além de cuidar do esgoto em boa parte de Minas Gerais.',
    oQueFaz: 'A Copasa capta água, trata, leva até as casas e coleta esgoto em centenas de cidades mineiras. Recebe por meio da conta de água paga pelos clientes.',
    vocesUsa: 'Se você mora em uma cidade mineira atendida pela Copasa, ela está por trás da torneira e do esgoto.',
    dono: 'Ser dono da Copasa é participar de um serviço essencial, regulado e ligado à saúde pública.',
    site: 'https://ri.copasa.com.br/',
    grupo: 'Saneamento',
  },
  {
    ticker: 'AURE3',
    nome: 'Auren Energia',
    emoji: '🌬️',
    setor: 'Energia elétrica',
    frase: 'Produz e vende energia de usinas hidrelétricas, eólicas e solares.',
    oQueFaz: 'A Auren gera eletricidade e negocia energia com grandes clientes. Seu portfólio combina fontes diferentes, o que ajuda a não depender de um único tipo de usina.',
    vocesUsa: 'A energia de uma empresa, fábrica ou comércio pode ter sido contratada com a Auren.',
    dono: 'Ser dono da Auren é participar de uma carteira de usinas e contratos de energia.',
    site: 'https://ri.aurenenergia.com.br/',
    grupo: 'Energia',
  },
  {
    ticker: 'CURY3',
    nome: 'Cury',
    emoji: '🏠',
    setor: 'Construção / Moradia',
    frase: 'Constrói apartamentos mais acessíveis, principalmente em São Paulo e no Rio de Janeiro.',
    oQueFaz: 'A Cury compra terrenos, lança prédios e vende apartamentos voltados à baixa e média renda. Muitos clientes usam programas habitacionais e financiamento para comprar.',
    vocesUsa: 'Um condomínio novo e mais acessível em São Paulo ou no Rio pode ter sido construído por ela.',
    dono: 'Ser dono da Cury é participar da venda de moradia para famílias que buscam o primeiro imóvel.',
    site: 'https://ri.cury.net/',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'EZTC3',
    nome: 'EZTEC',
    emoji: '🏙️',
    setor: 'Construção',
    frase: 'Constrói e vende prédios residenciais e comerciais, principalmente em São Paulo.',
    oQueFaz: 'A EZTEC compra terrenos, desenvolve projetos, constrói e vende as unidades. O resultado depende de vender bem os lançamentos e controlar o custo da obra.',
    vocesUsa: 'Um apartamento, escritório ou prédio novo na região de São Paulo pode levar a marca EZTEC.',
    dono: 'Ser dono da EZTEC é participar dos projetos imobiliários que ela consegue lançar e vender.',
    site: 'https://ri.eztec.com.br/',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'DIRR3',
    nome: 'Direcional',
    emoji: '🧱',
    setor: 'Construção / Moradia',
    frase: 'Constrói apartamentos para famílias de renda baixa e média em várias cidades do Brasil.',
    oQueFaz: 'A Direcional desenvolve e vende moradias, muitas delas ligadas a programas habitacionais. Também atua com a marca Riva, voltada a imóveis de padrão intermediário.',
    vocesUsa: 'Um condomínio financiado pelo Minha Casa Minha Vida pode ter sido construído por ela.',
    dono: 'Ser dono da Direcional é participar de projetos que transformam financiamento em casa própria.',
    site: 'https://ri.direcional.com.br/',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'MOVI3',
    nome: 'Movida',
    emoji: '🚙',
    setor: 'Aluguel de carros',
    frase: 'Aluga carros por dia ou por mais tempo e depois vende esses veículos como seminovos.',
    oQueFaz: 'A Movida compra uma frota grande, recebe pelo aluguel e, depois de um período, vende os carros usados. O negócio precisa equilibrar o valor do aluguel, o custo da dívida e o preço de revenda.',
    vocesUsa: 'Quando você aluga um carro numa viagem, contrata um carro por mês ou compra um seminovo da Movida.',
    dono: 'Ser dono da Movida é participar do aluguel e da renovação de uma frota de veículos.',
    site: 'https://ri.movida.com.br/',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'ECOR3',
    nome: 'EcoRodovias',
    emoji: '🛣️',
    setor: 'Rodovias',
    frase: 'Cuida de estradas e recebe pedágio de quem passa por elas.',
    oQueFaz: 'A EcoRodovias administra concessões rodoviárias: mantém, amplia e opera estradas por um prazo definido. Em troca, arrecada pedágio dos veículos que circulam.',
    vocesUsa: 'Quando você viaja por uma rodovia operada pela Ecovias, Ecopistas ou outra concessão do grupo.',
    dono: 'Ser dono da EcoRodovias é participar das receitas e dos custos de manter estradas concedidas.',
    site: 'https://ri.ecorodovias.com.br/',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'CCRO3',
    nome: 'Motiva',
    emoji: '🚇',
    setor: 'Mobilidade',
    frase: 'Opera rodovias, metrôs, trens e aeroportos que movimentam milhões de pessoas.',
    oQueFaz: 'A antiga CCR agora se chama Motiva. Ela administra concessões de transporte e recebe tarifas, pedágios e outras receitas para operar e melhorar essa infraestrutura.',
    vocesUsa: 'Quando você passa por uma rodovia, aeroporto, metrô ou trem administrado pelo grupo.',
    dono: 'Ser dono da Motiva é participar de concessões que ajudam pessoas e cargas a circular.',
    site: 'https://ri.motiva.com.br/',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'PSSA3',
    nome: 'Porto',
    emoji: '🛡️',
    setor: 'Seguros e Serviços',
    frase: 'Começou com seguro de carro e hoje também oferece saúde, banco e serviços para casa.',
    oQueFaz: 'A Porto recebe o pagamento dos seguros e cobre os prejuízos previstos nos contratos. Também ganha com cartões, financiamento, planos de saúde e serviços de assistência.',
    vocesUsa: 'Se você tem seguro do carro, chama um guincho, usa um cartão Porto ou contrata assistência residencial.',
    dono: 'Ser dono da Porto é participar de um negócio que cobra para proteger pessoas e bens contra imprevistos.',
    site: 'https://ri.portoseguro.com.br/',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'BBSE3',
    nome: 'BB Seguridade',
    emoji: '☂️',
    setor: 'Seguros',
    frase: 'Vende seguros, previdência e títulos de capitalização pela enorme rede do Banco do Brasil.',
    oQueFaz: 'A BB Seguridade reúne participações em negócios de seguros, previdência e capitalização. Sua grande vantagem é chegar aos clientes pelas agências e canais digitais do Banco do Brasil.',
    vocesUsa: 'Quando você contrata seguro rural, seguro de vida ou previdência pelos canais do Banco do Brasil.',
    dono: 'Ser dono da BB Seguridade é participar das comissões e resultados dos produtos de proteção vendidos pelo BB.',
    site: 'https://www.bbseguridaderi.com.br/',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'RAPT4',
    nome: 'Randoncorp',
    emoji: '🚚',
    setor: 'Indústria / Transporte',
    frase: 'Faz carretas, freios e outras peças que ajudam caminhões e cargas a rodar.',
    oQueFaz: 'A Randoncorp fabrica semirreboques e componentes para veículos comerciais, além de oferecer serviços financeiros ligados ao setor. Vende para transportadoras, montadoras e clientes no exterior.',
    vocesUsa: 'Quando você vê uma carreta Randon na estrada ou um veículo pesado com freios e peças das marcas do grupo.',
    dono: 'Ser dono da Randoncorp é participar da indústria que equipa o transporte de carga.',
    site: 'https://ri.randoncorp.com/',
    grupo: 'Indústria',
  },
  {
    ticker: 'KEPL3',
    nome: 'Kepler Weber',
    emoji: '🌽',
    setor: 'Agronegócio / Armazenagem',
    frase: 'Faz silos e equipamentos que guardam os grãos depois da colheita.',
    oQueFaz: 'A Kepler Weber fabrica sistemas para armazenar, limpar e transportar grãos dentro de fazendas, cooperativas e terminais. Ganha quando o agro investe para reduzir perdas e guardar melhor a safra.',
    vocesUsa: 'Você vê o trabalho dela nos grandes silos metálicos ao lado de fazendas e estradas.',
    dono: 'Ser dono da Kepler Weber é participar da infraestrutura que guarda a produção do campo.',
    site: 'https://ri.kepler.com.br/',
    grupo: 'Agro',
  },
  {
    ticker: 'MDIA3',
    nome: 'M. Dias Branco',
    emoji: '🍪',
    setor: 'Alimentos',
    frase: 'A dona de marcas de biscoito e macarrão como Piraquê, Adria, Vitarella e Fortaleza.',
    oQueFaz: 'A M. Dias Branco produz massas, biscoitos, farinhas e outros alimentos. Compra matérias-primas como trigo e óleo e vende produtos de marcas conhecidas em supermercados de todo o país.',
    vocesUsa: 'Quando você come um biscoito Piraquê, uma massa Adria ou produtos Vitarella e Fortaleza.',
    dono: 'Ser dono da M. Dias Branco é participar de alimentos simples que entram no carrinho de milhões de famílias.',
    site: 'https://ri.mdiasbranco.com.br/',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'NUBR33',
    nome: 'Nubank',
    emoji: '💜',
    setor: 'Banco digital',
    frase: 'O banco roxinho do celular — sem agência, sem fila e sem tarifa em quase tudo.',
    oQueFaz: 'O Nubank oferece conta, cartão, empréstimo e investimento direto pelo app, sem agência física. Ganha com juros do cartão e do crédito, e com taxas de serviço. Cresceu virando o primeiro banco de muita gente.',
    vocesUsa: 'Se você tem o cartão roxo, a conta ou a caixinha do Nubank no celular.',
    dono: 'Ser dono do Nubank é ter um pedaço do banco que tirou a fila da agência da vida das pessoas.',
    site: 'https://nubank.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'BHIA3',
    nome: 'Casas Bahia',
    emoji: '🛋️',
    setor: 'Varejo / Móveis e eletro',
    frase: 'A loja do carnê — sofá, geladeira e TV parcelados em vezes que cabem no bolso.',
    oQueFaz: 'O Grupo Casas Bahia (com Ponto e Extra.com) vende móvel e eletrodoméstico, muito no crediário próprio. Ganha na venda do produto e nos juros do parcelamento. É o varejo que atende quem não tem cartão.',
    vocesUsa: 'Quando você compra um sofá, uma geladeira ou uma TV nas Casas Bahia ou no Ponto.',
    dono: 'Ser dono das Casas Bahia é ficar com um pedaço da loja que mobiliou a casa do brasileiro.',
    site: 'https://www.casasbahia.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'PCAR3',
    nome: 'Pão de Açúcar',
    emoji: '🥖',
    setor: 'Supermercado',
    frase: 'A rede de supermercado de bairro e de alto padrão — o mercado da esquina que virou marca.',
    oQueFaz: 'O GPA opera supermercados Pão de Açúcar e Minuto. Vende comida e produto de casa, com foco em público de renda média e alta. Ganha em volume, com margem apertada típica de mercado.',
    vocesUsa: 'Toda vez que você faz compra num Pão de Açúcar ou passa num Minuto pra resolver o jantar.',
    dono: 'Ser dono do GPA é ficar com um pedacinho da compra semanal de milhares de famílias.',
    site: 'https://www.gpabr.com',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'GUAR3',
    nome: 'Riachuelo',
    emoji: '👕',
    setor: 'Varejo / Roupa',
    frase: 'A dona da Riachuelo — roupa de shopping com preço acessível, e o cartão da loja junto.',
    oQueFaz: 'A Guararapes é dona da Riachuelo. Fabrica boa parte da própria roupa (tem fábrica no Nordeste), vende nas lojas e ainda ganha com o cartão Riachuelo, que financia a compra do cliente.',
    vocesUsa: 'Quando você compra uma roupa na Riachuelo ou parcela no cartão da loja.',
    dono: 'Ser dono da Guararapes é ter um pedaço da fábrica e da loja ao mesmo tempo.',
    site: 'https://www.riachuelo.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'CEAB3',
    nome: 'C&A',
    emoji: '👖',
    setor: 'Varejo / Roupa',
    frase: 'A loja de roupa de shopping conhecida pelas coleções baratas que giram rápido.',
    oQueFaz: 'A C&A vende moda para família inteira, com coleções novas o tempo todo e preço acessível. Ganha em cada peça vendida e também com serviços financeiros ligados ao cartão.',
    vocesUsa: 'Quando você compra uma camiseta, uma calça ou roupa das crianças na C&A.',
    dono: 'Ser dono da C&A é ficar com um pedacinho de cada peça que sai da arara.',
    site: 'https://www.cea.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'GRND3',
    nome: 'Grendene',
    emoji: '👡',
    setor: 'Calçados',
    frase: 'A dona da Melissa, Ipanema, Rider e Grendha — o chinelo e a sandália de plástico do Brasil.',
    oQueFaz: 'A Grendene fabrica calçado de plástico e borracha no Ceará e vende no Brasil e no exterior. Ganha em cada par. É conhecida por ter pouca dívida e muito caixa guardado.',
    vocesUsa: 'Se você já usou uma Melissa, uma sandália Ipanema ou um chinelo Rider.',
    dono: 'Ser dono da Grendene é ter um pedaço das sandálias que calçam o verão brasileiro.',
    site: 'https://www.grendene.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'VULC3',
    nome: 'Vulcabras',
    emoji: '👟',
    setor: 'Calçados / Esporte',
    frase: 'A dona da Olympikus e da Mizuno no Brasil — o tênis de corrida que você vê na rua.',
    oQueFaz: 'A Vulcabras fabrica e vende tênis esportivo das marcas Olympikus, Mizuno e Under Armour no Brasil. Ganha em cada par vendido, montada em fábricas próprias no Nordeste.',
    vocesUsa: 'Se você corre, treina ou anda de tênis Olympikus ou Mizuno.',
    dono: 'Ser dono da Vulcabras é ter um pedaço do tênis que o Brasil calça pra treinar.',
    site: 'https://www.vulcabras.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'SBFG3',
    nome: 'Centauro',
    emoji: '⚽',
    setor: 'Varejo / Esporte',
    frase: 'A maior loja de artigo esportivo do Brasil — e a operadora da Nike por aqui.',
    oQueFaz: 'O Grupo SBF é dono da Centauro e opera a Nike no Brasil. Vende tênis, camisa de time e equipamento esportivo em loja e no app. Ganha na revenda e nas marcas próprias.',
    vocesUsa: 'Quando você compra a camisa do seu time, um tênis ou uma bola na Centauro.',
    dono: 'Ser dono do Grupo SBF é ficar com um pedaço do que o Brasil gasta com esporte.',
    site: 'https://www.gruposbf.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'ZAMP3',
    nome: 'Zamp (Burger King)',
    emoji: '🍟',
    setor: 'Alimentação / Fast-food',
    frase: 'A operadora do Burger King e do Popeyes no Brasil — o lanche do shopping e da estrada.',
    oQueFaz: 'A Zamp opera as lojas do Burger King e do Popeyes no país, pagando royalties às marcas. Ganha em cada combo vendido, no balcão, no drive-thru e no delivery.',
    vocesUsa: 'Toda vez que você come um Whopper ou pede Burger King pelo aplicativo.',
    dono: 'Ser dono da Zamp é ficar com um pedaço de cada lanche servido no balcão.',
    site: 'https://www.zampbr.com.br',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'MEAL3',
    nome: 'IMC',
    emoji: '🍕',
    setor: 'Alimentação / Restaurantes',
    frase: 'A dona do Frango Assado da estrada e operadora de KFC e Pizza Hut no Brasil.',
    oQueFaz: 'A IMC opera restaurantes em rodovias, aeroportos e shoppings — Frango Assado, KFC, Pizza Hut. Ganha servindo refeição a quem está em trânsito, um público que sempre passa.',
    vocesUsa: 'Quando você para no Frango Assado numa viagem, ou come KFC no shopping.',
    dono: 'Ser dono da IMC é ter um pedaço da parada obrigatória da estrada.',
    site: 'https://www.internationalmealcompany.com',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'HYPE3',
    nome: 'Hypera Pharma',
    emoji: '🤒',
    setor: 'Farmacêutica',
    frase: 'A dona de Neosaldina, Engov, Buscopan e Benegrip — o remédio do armarinho da sua casa.',
    oQueFaz: 'A Hypera desenvolve e vende medicamentos de marca que a gente compra sem receita, além de genéricos. Ganha porque as marcas são conhecidas e a pessoa pede pelo nome na farmácia.',
    vocesUsa: 'Quando você toma uma Neosaldina pra dor de cabeça ou um Engov depois da festa.',
    dono: 'Ser dono da Hypera é ter um pedaço dos remédios que o brasileiro pede pelo nome.',
    site: 'https://www.hypera.com.br',
    grupo: 'Saúde',
  },
  {
    ticker: 'RDOR3',
    nome: "Rede D'Or",
    emoji: '🩹',
    setor: 'Saúde / Hospitais',
    frase: 'A maior rede de hospitais privados do Brasil — onde muita gente nasce e se trata.',
    oQueFaz: "A Rede D'Or é dona de dezenas de hospitais e recebe dos planos de saúde por cada atendimento, cirurgia e internação. Também tem seguradora própria. Ganha com volume de atendimento.",
    vocesUsa: 'Se você já se consultou, operou ou visitou alguém num hospital da rede.',
    dono: "Ser dono da Rede D'Or é ter um pedaço da estrutura que atende o Brasil quando ele adoece.",
    site: 'https://www.rededorsaoluiz.com.br',
    grupo: 'Saúde',
  },
  {
    ticker: 'QUAL3',
    nome: 'Qualicorp',
    emoji: '📋',
    setor: 'Saúde / Plano',
    frase: 'A empresa que vende plano de saúde coletivo por associação e sindicato.',
    oQueFaz: 'A Qualicorp administra e vende planos de saúde por adesão — aqueles que você contrata via categoria profissional. Ganha uma comissão sobre a mensalidade de cada beneficiário.',
    vocesUsa: 'Se você tem plano de saúde contratado pelo seu sindicato ou conselho de classe.',
    dono: 'Ser dono da Qualicorp é receber um pedaço da comissão dos planos por adesão.',
    site: 'https://www.qualicorp.com.br',
    grupo: 'Saúde',
  },
  {
    ticker: 'PGMN3',
    nome: 'Pague Menos',
    emoji: '🏪',
    setor: 'Farmácia',
    frase: 'Uma das maiores redes de farmácia do país, muito forte no Norte e Nordeste.',
    oQueFaz: 'A Pague Menos vende remédio, higiene e beleza em milhares de lojas, e é dona da Extrafarma. Ganha um pouquinho em cada caixa, com volume alto e presença onde outras redes não chegam.',
    vocesUsa: 'Quando você compra remédio ou produto de higiene numa Pague Menos ou Extrafarma.',
    dono: 'Ser dono da Pague Menos é ter um pedaço da farmácia que atende o Brasil profundo.',
    site: 'https://www.paguemenos.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'INTB3',
    nome: 'Intelbras',
    emoji: '📷',
    setor: 'Eletrônicos / Segurança',
    frase: 'A empresa da câmera de segurança, do interfone e do roteador de internet da sua casa.',
    oQueFaz: 'A Intelbras fabrica equipamento de segurança eletrônica, rede, telefonia e energia solar. Vende pra casa, comércio e condomínio. Ganha em cada equipamento — e o Brasil compra muita segurança.',
    vocesUsa: 'A câmera do seu prédio, o interfone ou o roteador de casa tem boa chance de ser Intelbras.',
    dono: 'Ser dono da Intelbras é ter um pedaço da empresa que vigia e conecta as casas brasileiras.',
    site: 'https://www.intelbras.com.br',
    grupo: 'Tecnologia e Telecom',
  },
  {
    ticker: 'POSI3',
    nome: 'Positivo',
    emoji: '🖥️',
    setor: 'Tecnologia / Computadores',
    frase: 'A fabricante brasileira de computador — o notebook da escola e do programa do governo.',
    oQueFaz: 'A Positivo monta computador, notebook e celular no Brasil, vendendo pro varejo, pra empresa e pra órgão público (licitação de escola). Ganha em cada máquina montada e vendida.',
    vocesUsa: 'Se você teve um computador Positivo em casa ou usou um na escola pública.',
    dono: 'Ser dono da Positivo é ter um pedaço do computador que informatizou muita casa brasileira.',
    site: 'https://www.positivotecnologia.com.br',
    grupo: 'Tecnologia e Telecom',
  },
  {
    ticker: 'BRKM5',
    nome: 'Braskem',
    emoji: '🧴',
    setor: 'Química / Plástico',
    frase: 'A maior fabricante de plástico da América — a matéria-prima da embalagem e do balde.',
    oQueFaz: 'A Braskem transforma derivado de petróleo e gás em resina plástica, que a indústria usa pra fazer embalagem, cano, brinquedo e peça de carro. Vende pra fábrica, não pro consumidor.',
    vocesUsa: 'A garrafa, o pote de margarina e o cano da sua casa começaram como resina dela.',
    dono: 'Ser dono da Braskem é ter um pedaço da matéria-prima de quase todo plástico do país.',
    site: 'https://www.braskem.com.br',
    grupo: 'Indústria',
  },
  {
    ticker: 'VBBR3',
    nome: 'Vibra (Posto BR)',
    emoji: '🟢',
    setor: 'Combustível',
    frase: 'A dona dos postos BR — a maior distribuidora de combustível do Brasil.',
    oQueFaz: 'A Vibra compra combustível das refinarias e distribui para milhares de postos BR, além de vender direto pra empresa e aviação. Ganha uma margem em cada litro que passa por ela.',
    vocesUsa: 'Toda vez que você abastece num posto com a bandeira BR.',
    dono: 'Ser dono da Vibra é ficar com um pedaço de cada litro distribuído pelo país.',
    site: 'https://www.vibraenergia.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'CPLE6',
    nome: 'Copel',
    emoji: '🔋',
    setor: 'Energia elétrica',
    frase: 'A empresa de energia do Paraná — a conta de luz do paranaense.',
    oQueFaz: 'A Copel gera, transmite e distribui energia elétrica no Paraná. Você paga a conta todo mês. É serviço essencial e regulado, com receita bastante previsível.',
    vocesUsa: 'Se você mora no Paraná e acende a luz, é Copel na conta.',
    dono: 'Ser dono da Copel é receber um pedaço da conta de luz do Paraná.',
    site: 'https://www.copel.com',
    grupo: 'Energia',
  },
  {
    ticker: 'NEOE3',
    nome: 'Neoenergia',
    emoji: '🔆',
    setor: 'Energia elétrica',
    frase: 'Distribui a luz em vários estados — Bahia, Pernambuco, Rio Grande do Norte e São Paulo.',
    oQueFaz: 'A Neoenergia gera, transmite e distribui energia em várias regiões, além de investir em eólicas. Recebe pela conta de luz de milhões de clientes, num negócio regulado e de longo prazo.',
    vocesUsa: 'Se sua conta de luz vem da Coelba, Celpe, Cosern ou Elektro, é do grupo dela.',
    dono: 'Ser dono da Neoenergia é receber um pedaço da conta de luz de vários estados.',
    site: 'https://www.neoenergia.com',
    grupo: 'Energia',
  },
  {
    ticker: 'SAPR11',
    nome: 'Sanepar',
    emoji: '🚰',
    setor: 'Água e Saneamento',
    frase: 'A empresa que leva água tratada e esgoto pro Paraná — a conta de água de lá.',
    oQueFaz: 'A Sanepar capta, trata e distribui água e cuida do esgoto em quase todas as cidades do Paraná. Recebe a conta todo mês. Serviço essencial, previsível e conhecido por pagar dividendo.',
    vocesUsa: 'Se você mora no Paraná e abre a torneira, é Sanepar por trás.',
    dono: 'Ser dono da Sanepar é receber um pedaço da conta de água do Paraná.',
    site: 'https://site.sanepar.com.br',
    grupo: 'Saneamento',
  },
  {
    ticker: 'GOLL4',
    nome: 'Gol',
    emoji: '🛩️',
    setor: 'Aviação',
    frase: 'A companhia aérea das listas laranja — muito forte na ponte aérea Rio–São Paulo.',
    oQueFaz: 'A Gol transporta passageiros pelo Brasil e para alguns destinos no exterior, vendendo passagem e serviços a bordo. É um setor duro: depende de combustível, dólar e do bolso do passageiro.',
    vocesUsa: 'Toda vez que você voa de Gol ou acumula milhas no Smiles.',
    dono: 'Ser dono da Gol é ter um pedaço de uma das aéreas que ligam o país.',
    site: 'https://www.voegol.com.br',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'STBP3',
    nome: 'Santos Brasil',
    emoji: '⚓',
    setor: 'Portos / Logística',
    frase: 'A empresa do porto — move os contêineres que entram e saem do Brasil em Santos.',
    oQueFaz: 'A Santos Brasil opera terminais portuários, descarregando e armazenando contêineres. Cobra por cada movimentação. Quanto mais o Brasil importa e exporta, mais caixa passa por ela.',
    vocesUsa: 'Quase todo produto importado que você compra passou por um porto como o dela.',
    dono: 'Ser dono da Santos Brasil é ter um pedaço da porta de entrada do comércio brasileiro.',
    site: 'https://www.santosbrasil.com.br',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'VAMO3',
    nome: 'Vamos',
    emoji: '🚚',
    setor: 'Aluguel de caminhões',
    frase: 'A maior locadora de caminhão e máquina agrícola do Brasil — aluguel pra quem trabalha.',
    oQueFaz: 'A Vamos aluga caminhão, ônibus, trator e máquina pesada pra empresa, em contratos longos. A empresa prefere alugar a comprar. Ganha no aluguel e na revenda do usado.',
    vocesUsa: 'O caminhão que entrega mercadoria na sua cidade pode ser alugado dela.',
    dono: 'Ser dono da Vamos é ter um pedaço da frota pesada que move a economia.',
    site: 'https://www.grupovamos.com.br',
    grupo: 'Transporte e Logística',
  },
  {
    ticker: 'TEND3',
    nome: 'Tenda',
    emoji: '🏡',
    setor: 'Construção / Casa popular',
    frase: 'Construtora focada no apartamento popular, do Minha Casa Minha Vida.',
    oQueFaz: 'A Tenda constrói e vende apartamento de baixa renda, com processo padronizado pra baratear a obra. Depende muito do crédito habitacional e do programa do governo.',
    vocesUsa: 'Se alguém que você conhece comprou o primeiro apartamento financiado.',
    dono: 'Ser dono da Tenda é ter um pedaço da primeira casa própria de muita família.',
    site: 'https://www.tenda.com',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'IGTI11',
    nome: 'Iguatemi',
    emoji: '🏙️',
    setor: 'Shopping centers',
    frase: 'A dona de shoppings de alto padrão — recebe aluguel das lojas de grife.',
    oQueFaz: 'A Iguatemi é dona e administradora de shoppings sofisticados. Ela não vende nas lojas: recebe aluguel, condomínio e estacionamento. Ganha mesmo quando a loja tem um mês fraco.',
    vocesUsa: 'Quando você passeia, come ou estaciona num shopping Iguatemi.',
    dono: 'Ser dono da Iguatemi é ser dono do shopping, não da loja — o aluguel vem pra você.',
    site: 'https://www.iguatemi.com.br',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'ALOS3',
    nome: 'Allos',
    emoji: '🎠',
    setor: 'Shopping centers',
    frase: 'Uma das maiores donas de shopping do país, nascida da união de Aliansce e BR Malls.',
    oQueFaz: 'A Allos administra dezenas de shoppings pelo Brasil e vive do aluguel pago pelas lojas, mais estacionamento e mídia nos corredores. Negócio de imóvel, não de varejo.',
    vocesUsa: 'Muito provável que o shopping que você frequenta seja administrado por ela.',
    dono: 'Ser dono da Allos é receber um pedaço do aluguel dos shoppings do Brasil.',
    site: 'https://www.allos.co',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'JHSF3',
    nome: 'JHSF',
    emoji: '🥂',
    setor: 'Imóveis de luxo',
    frase: 'A empresa do luxo — shopping Cidade Jardim, hotel Fasano e aeroporto executivo.',
    oQueFaz: 'A JHSF incorpora imóveis de altíssimo padrão, opera shoppings de luxo, hotéis Fasano e um aeroporto executivo. Ganha vendendo imóvel caro e cobrando por serviços premium.',
    vocesUsa: 'Se já passou pelo Cidade Jardim, jantou num Fasano ou viu o aeroporto de Bragança.',
    dono: 'Ser dono da JHSF é ter um pedaço do mercado de luxo brasileiro.',
    site: 'https://www.jhsf.com.br',
    grupo: 'Construção e Imóveis',
  },
  {
    ticker: 'ESPA3',
    nome: 'Espaçolaser',
    emoji: '✨',
    setor: 'Serviços / Estética',
    frase: 'A maior rede de depilação a laser do mundo — aquela loja de quiosque no shopping.',
    oQueFaz: 'A Espaçolaser vende pacotes de sessões de depilação a laser em centenas de lojas. O cliente paga parcelado e volta várias vezes. Ganha com volume e com recorrência do tratamento.',
    vocesUsa: 'Se você já fez (ou viu a fila de) depilação a laser no shopping.',
    dono: 'Ser dono da Espaçolaser é ter um pedaço de um serviço que virou hábito de consumo.',
    site: 'https://www.espacolaser.com.br',
    grupo: 'Serviços',
  },
  {
    ticker: 'ANIM3',
    nome: 'Ânima Educação',
    emoji: '🎒',
    setor: 'Educação',
    frase: 'Dona de faculdades como Una, UniBH, São Judas e Inspirali (medicina).',
    oQueFaz: 'A Ânima tem universidades particulares e é forte em cursos de medicina, que têm mensalidade alta. Vive das mensalidades dos alunos e de financiamento estudantil.',
    vocesUsa: 'Se você estudou na Una, UniBH, São Judas ou numa faculdade do grupo.',
    dono: 'Ser dono da Ânima é receber um pedaço das mensalidades de quem está se formando.',
    site: 'https://www.animaeducacao.com.br',
    grupo: 'Educação',
  },
  {
    ticker: 'SEER3',
    nome: 'Ser Educacional',
    emoji: '📖',
    setor: 'Educação',
    frase: 'Grupo de faculdades forte no Nordeste — UNINASSAU, UNAMA e outras.',
    oQueFaz: 'A Ser Educacional tem faculdades presenciais e a distância, concentradas no Norte e Nordeste. Ganha com mensalidade e cresce abrindo polos de ensino a distância em cidades menores.',
    vocesUsa: 'Se você ou alguém da família estudou na UNINASSAU ou na UNAMA.',
    dono: 'Ser dono da Ser Educacional é ter um pedaço do acesso ao diploma no Nordeste.',
    site: 'https://www.sereducacional.com',
    grupo: 'Educação',
  },
  {
    ticker: 'CAML3',
    nome: 'Camil',
    emoji: '🍚',
    setor: 'Alimentos',
    frase: 'A dona do arroz Camil, do feijão Camil e do açúcar União — a base do prato brasileiro.',
    oQueFaz: 'A Camil compra, empacota e vende alimento básico: arroz, feijão, açúcar, café e pescado, com marcas conhecidas. Ganha um pouquinho em cada pacote, mas vende em altíssimo volume.',
    vocesUsa: 'Quando você cozinha arroz Camil ou adoça o café com açúcar União.',
    dono: 'Ser dono da Camil é ter um pedaço do arroz com feijão que o Brasil come todo dia.',
    site: 'https://www.camilalimentos.com.br',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'BEEF3',
    nome: 'Minerva Foods',
    emoji: '🐂',
    setor: 'Alimentos / Carne',
    frase: 'Uma das maiores exportadoras de carne bovina da América do Sul.',
    oQueFaz: 'A Minerva abate boi e exporta carne pro mundo, principalmente Ásia e Oriente Médio. Ganha em dólar, então o câmbio pesa muito no resultado dela.',
    vocesUsa: 'A carne brasileira que chega na mesa de outros países passa por empresas como ela.',
    dono: 'Ser dono da Minerva é ter um pedaço da carne que o Brasil vende pro mundo.',
    site: 'https://www.minervafoods.com',
    grupo: 'Alimentos e Bebidas',
  },
  {
    ticker: 'SMTO3',
    nome: 'São Martinho',
    emoji: '🍬',
    setor: 'Açúcar e Etanol',
    frase: 'Uma das maiores usinas de cana do Brasil — faz o açúcar e o etanol do posto.',
    oQueFaz: 'A São Martinho planta e moe cana pra produzir açúcar e etanol, além de gerar energia com o bagaço. Ganha com o preço do açúcar no mercado internacional e do etanol aqui dentro.',
    vocesUsa: 'O açúcar do seu café e o etanol que você coloca no carro saem de usinas como essa.',
    dono: 'Ser dono da São Martinho é ter um pedaço da cana que vira doce e combustível.',
    site: 'https://www.saomartinho.com.br',
    grupo: 'Agro',
  },
  {
    ticker: 'AGRO3',
    nome: 'BrasilAgro',
    emoji: '🚜',
    setor: 'Agronegócio / Terras',
    frase: 'Compra terra bruta, transforma em fazenda produtiva e depois vende mais cara.',
    oQueFaz: 'A BrasilAgro adquire terras pouco produtivas, investe pra torná-las agrícolas e planta soja, milho e cana. Ganha com a safra e, principalmente, com a valorização da terra ao vendê-la.',
    vocesUsa: 'Não diretamente — mas a comida e o etanol do país vêm de terras como essas.',
    dono: 'Ser dono da BrasilAgro é ser dono de terra brasileira sendo transformada em fazenda.',
    site: 'https://www.brasil-agro.com',
    grupo: 'Agro',
  },
  {
    ticker: 'TTEN3',
    nome: '3tentos',
    emoji: '🌽',
    setor: 'Agronegócio',
    frase: 'Vende insumo pro produtor rural, compra o grão dele e ainda produz biodiesel.',
    oQueFaz: 'A 3tentos atende o agricultor do começo ao fim: vende semente e adubo, recebe a soja como pagamento e transforma o grão em farelo, óleo e biodiesel. Ganha nas três pontas.',
    vocesUsa: 'O biodiesel misturado no diesel do caminhão sai de empresas como ela.',
    dono: 'Ser dono da 3tentos é acompanhar o agro do plantio até o combustível.',
    site: 'https://www.3tentos.com.br',
    grupo: 'Agro',
  },
  {
    ticker: 'TUPY3',
    nome: 'Tupy',
    emoji: '🔧',
    setor: 'Indústria / Autopeças',
    frase: 'Faz o bloco de motor de caminhão vendido pras montadoras do mundo inteiro.',
    oQueFaz: 'A Tupy funde ferro pra fabricar bloco e cabeçote de motor, principalmente pra veículo pesado. Vende pras grandes montadoras, muito no exterior. Ganha em dólar.',
    vocesUsa: 'O motor do caminhão que transporta sua comida pode ter peça fundida por ela.',
    dono: 'Ser dono da Tupy é ter um pedaço da fundição brasileira que abastece montadora global.',
    site: 'https://www.tupy.com.br',
    grupo: 'Indústria',
  },
  {
    ticker: 'LEVE3',
    nome: 'Mahle Metal Leve',
    emoji: '🛞',
    setor: 'Indústria / Autopeças',
    frase: 'Faz pistão, filtro e anel do motor — a peça que a oficina troca na revisão.',
    oQueFaz: 'A Metal Leve produz componentes de motor pras montadoras e também pro mercado de reposição (a peça da oficina). O segundo é mais rentável e não depende de carro novo.',
    vocesUsa: 'Quando o mecânico troca o filtro ou peça do motor do seu carro.',
    dono: 'Ser dono da Metal Leve é ter um pedaço da peça que mantém os carros rodando.',
    site: 'https://www.mahle.com.br',
    grupo: 'Indústria',
  },
  {
    ticker: 'MYPK3',
    nome: 'Iochpe-Maxion',
    emoji: '🚙',
    setor: 'Indústria / Autopeças',
    frase: 'A maior fabricante de rodas do mundo — a roda do seu carro e do caminhão.',
    oQueFaz: 'A Iochpe-Maxion produz rodas de aço e alumínio e chassis, vendendo pras montadoras no mundo todo. Depende do quanto a indústria automotiva está produzindo.',
    vocesUsa: 'As rodas do seu carro têm boa chance de terem saído de uma fábrica dela.',
    dono: 'Ser dono da Iochpe é ter um pedaço das rodas que rodam pelo planeta.',
    site: 'https://www.iochpe.com.br',
    grupo: 'Indústria',
  },
  {
    ticker: 'FRAS3',
    nome: 'Fras-le',
    emoji: '🛑',
    setor: 'Indústria / Autopeças',
    frase: 'Faz a pastilha e a lona de freio — a peça que faz o carro parar.',
    oQueFaz: 'A Fras-le fabrica material de fricção (freio) pra carro, caminhão e ônibus, com forte presença no mercado de reposição. Peça de freio se gasta sempre, então a demanda se repete.',
    vocesUsa: 'Quando você troca a pastilha de freio do carro na oficina.',
    dono: 'Ser dono da Fras-le é ter um pedaço da peça que todo veículo precisa trocar.',
    site: 'https://www.fras-le.com',
    grupo: 'Indústria',
  },
  {
    ticker: 'UNIP6',
    nome: 'Unipar',
    emoji: '🧪',
    setor: 'Química',
    frase: 'Faz o cloro que trata a água da sua cidade e a soda usada pela indústria.',
    oQueFaz: 'A Unipar produz cloro, soda cáustica e PVC. O cloro trata água e piscina; a soda serve a várias indústrias; o PVC vira cano. Vende pra empresa e pra saneamento, não pro consumidor.',
    vocesUsa: 'A água tratada que sai da sua torneira usou cloro de empresas como essa.',
    dono: 'Ser dono da Unipar é ter um pedaço do que trata a água e sustenta a indústria.',
    site: 'https://www.unipar.com',
    grupo: 'Indústria',
  },
  {
    ticker: 'IRBR3',
    nome: 'IRB Brasil RE',
    emoji: '🛡️',
    setor: 'Resseguros',
    frase: 'É o seguro do seguro — quem cobre as seguradoras quando o prejuízo é grande demais.',
    oQueFaz: 'O IRB faz resseguro: as seguradoras pagam a ele pra dividir o risco de sinistros enormes (uma safra perdida, um avião, uma usina). Ganha com o prêmio recebido menos o que precisa pagar.',
    vocesUsa: 'Indiretamente: o seguro do seu carro ou da sua casa é sustentado por essa camada.',
    dono: 'Ser dono do IRB é participar da última rede de proteção do sistema de seguros.',
    site: 'https://www.irbre.com',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'CXSE3',
    nome: 'Caixa Seguridade',
    emoji: '🧾',
    setor: 'Seguros',
    frase: 'O braço de seguros da Caixa — vende seguro e consórcio na boca do caixa.',
    oQueFaz: 'A Caixa Seguridade vende seguro de vida, residencial, prestamista e consórcio usando a rede gigantesca de agências da Caixa. Ganha comissão sem precisar montar loja própria.',
    vocesUsa: 'Se você fez financiamento ou consórcio na Caixa e levou o seguro junto.',
    dono: 'Ser dono da Caixa Seguridade é receber um pedaço do seguro vendido no balcão da Caixa.',
    site: 'https://www.caixaseguridade.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'BRSR6',
    nome: 'Banrisul',
    emoji: '🟩',
    setor: 'Banco',
    frase: 'O banco do estado do Rio Grande do Sul — o banco da praça no interior gaúcho.',
    oQueFaz: 'O Banrisul faz conta, crédito consignado e financiamento, muito concentrado no Sul. Ganha com juros e tarifas, e é onde cai o salário de boa parte do funcionalismo gaúcho.',
    vocesUsa: 'Se você mora no Rio Grande do Sul e tem conta ou empréstimo no Banrisul.',
    dono: 'Ser dono do Banrisul é ter um pedaço do banco mais enraizado do Sul.',
    site: 'https://www.banrisul.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'BMGB4',
    nome: 'Banco BMG',
    emoji: '🧡',
    setor: 'Banco',
    frase: 'O banco do empréstimo consignado — aquele descontado direto da folha ou do INSS.',
    oQueFaz: 'O BMG é forte em crédito consignado, em que a parcela sai direto do salário ou do benefício. Como o risco de calote é menor, o juro é mais baixo, e ele ganha no volume emprestado.',
    vocesUsa: 'Se você ou um aposentado da família já fez empréstimo descontado em folha.',
    dono: 'Ser dono do BMG é receber um pedaço dos juros do crédito consignado.',
    site: 'https://www.bancobmg.com.br',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'WIZC3',
    nome: 'Wiz Co',
    emoji: '📑',
    setor: 'Seguros / Corretagem',
    frase: 'Corretora que vende seguro dentro do canal dos outros — banco, loja, concessionária.',
    oQueFaz: 'A Wiz monta e opera a venda de seguros dentro de parceiros (bancos, varejo, montadora). Não carrega o risco do seguro: ganha comissão por cada apólice vendida no balcão do parceiro.',
    vocesUsa: 'Quando te oferecem um seguro junto com o financiamento ou a compra.',
    dono: 'Ser dono da Wiz é ficar com um pedaço da comissão do seguro vendido no balcão.',
    site: 'https://www.wiz.co',
    grupo: 'Bancos e Seguros',
  },
  {
    ticker: 'ORVR3',
    nome: 'Orizon',
    emoji: '♻️',
    setor: 'Resíduos / Ambiental',
    frase: 'Trata o lixo da cidade e transforma parte dele em energia e crédito de carbono.',
    oQueFaz: 'A Orizon opera aterros sanitários e ecoparques: recebe o lixo urbano (e cobra por isso), captura o gás pra gerar energia e vende crédito de carbono. Ganha três vezes com o mesmo resíduo.',
    vocesUsa: 'O lixo que sai da sua casa pode terminar num aterro operado por ela.',
    dono: 'Ser dono da Orizon é ter um pedaço do que a cidade joga fora — e do que se aproveita disso.',
    site: 'https://www.orizonvr.com.br',
    grupo: 'Serviços',
  },
  {
    ticker: 'AMBP3',
    nome: 'Ambipar',
    emoji: '🌍',
    setor: 'Ambiental / Emergências',
    frase: 'A empresa que corre pra conter vazamento e acidente ambiental — o bombeiro da indústria.',
    oQueFaz: 'A Ambipar atende emergências ambientais (vazamento químico, acidente com carga) e gerencia resíduos de empresas. É contratada por indústria e transportadora que precisam estar preparadas.',
    vocesUsa: 'Quando um caminhão tomba na estrada com carga química, equipes assim são acionadas.',
    dono: 'Ser dono da Ambipar é ter um pedaço do serviço que limpa a sujeira da indústria.',
    site: 'https://www.ambipar.com',
    grupo: 'Serviços',
  },
  {
    ticker: 'RECV3',
    nome: 'PetroRecôncavo',
    emoji: '⚗️',
    setor: 'Petróleo',
    frase: 'Pega poço de petróleo velho que a Petrobras deixou e faz ele produzir de novo.',
    oQueFaz: 'A PetroRecôncavo compra campos maduros em terra (Bahia, Rio Grande do Norte) e usa técnica pra extrair o petróleo que ainda restou. Custa menos que furar poço novo no mar.',
    vocesUsa: 'Indiretamente: parte do petróleo nacional vem desses campos reaproveitados.',
    dono: 'Ser dono da PetroRecôncavo é apostar em tirar valor do que outros já descartaram.',
    site: 'https://www.petroreconcavo.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'DESK3',
    nome: 'Desktop',
    emoji: '📡',
    setor: 'Internet / Provedor',
    frase: 'Provedor de internet de fibra no interior de São Paulo — o wi-fi da casa.',
    oQueFaz: 'A Desktop leva internet de fibra ótica pra casas e empresas em cidades do interior paulista. Cobra mensalidade. Receita recorrente: quase ninguém corta a internet de casa.',
    vocesUsa: 'Se a fibra da sua casa é de um provedor regional como esse.',
    dono: 'Ser dono da Desktop é receber um pedaço da mensalidade da internet do interior.',
    site: 'https://www.desktop.com.br',
    grupo: 'Tecnologia e Telecom',
  },
  {
    ticker: 'PNVL3',
    nome: 'Panvel',
    emoji: '💚',
    setor: 'Farmácia',
    frase: 'A rede de farmácia mais conhecida do Sul — a Panvel da esquina gaúcha.',
    oQueFaz: 'A Dimed opera as farmácias Panvel, além de distribuir medicamentos. Vende remédio, higiene e beleza, com marca própria forte. Ganha em volume e na fidelidade do cliente da região.',
    vocesUsa: 'Se você mora no Sul e compra remédio ou dermocosmético na Panvel.',
    dono: 'Ser dono da Dimed é ter um pedaço da farmácia de bairro do Sul do país.',
    site: 'https://www.panvel.com',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'MATD3',
    nome: 'Mater Dei',
    emoji: '🚑',
    setor: 'Saúde / Hospitais',
    frase: 'Rede de hospitais nascida em Minas Gerais, conhecida pelo atendimento de alto padrão.',
    oQueFaz: 'A Mater Dei opera hospitais e recebe dos planos de saúde por consulta, exame, cirurgia e internação. Cresce comprando hospitais em outras regiões e ampliando leitos.',
    vocesUsa: 'Se você já se tratou num hospital Mater Dei em Minas ou nas outras praças.',
    dono: 'Ser dono da Mater Dei é ter um pedaço da estrutura hospitalar privada do país.',
    site: 'https://www.materdei.com.br',
    grupo: 'Saúde',
  },
  {
    ticker: 'ALLD3',
    nome: 'Allied',
    emoji: '🔌',
    setor: 'Varejo / Eletrônicos',
    frase: 'Distribui e vende celular e eletrônico das grandes marcas — inclusive as lojas iPlace.',
    oQueFaz: 'A Allied distribui aparelho eletrônico pro varejo e opera lojas próprias (como iPlace, de produtos Apple). Ganha na margem entre comprar do fabricante e revender.',
    vocesUsa: 'Se você comprou um celular numa loja iPlace ou num varejo abastecido por ela.',
    dono: 'Ser dono da Allied é ficar com um pedaço do caminho entre a fábrica e a loja de celular.',
    site: 'https://www.alliedbrasil.com.br',
    grupo: 'Varejo e Consumo',
  },
  {
    ticker: 'LIGT3',
    nome: 'Light',
    emoji: '🔦',
    setor: 'Energia elétrica',
    frase: 'A distribuidora de energia do Rio de Janeiro — a conta de luz do carioca.',
    oQueFaz: 'A Light distribui energia elétrica na região do Rio. Recebe a conta de luz todo mês, mas enfrenta um desafio grande de perdas (gato de luz) e inadimplência na área que atende.',
    vocesUsa: 'Se você mora no Rio e paga conta de luz, é Light por trás.',
    dono: 'Ser dono da Light é ter um pedaço da distribuição de energia numa das maiores cidades do país.',
    site: 'https://www.light.com.br',
    grupo: 'Energia',
  },
  {
    ticker: 'ARML3',
    nome: 'Armac',
    emoji: '🚧',
    setor: 'Aluguel de máquinas',
    frase: 'Aluga escavadeira e trator pra obra e mineradora — máquina pesada por assinatura.',
    oQueFaz: 'A Armac aluga máquina pesada com operador e manutenção inclusos. A construtora prefere alugar a comprar equipamento caro. Ganha no contrato de locação de longo prazo.',
    vocesUsa: 'A escavadeira daquela obra na sua rua pode ser alugada, não da construtora.',
    dono: 'Ser dono da Armac é ter um pedaço das máquinas que levantam as obras do país.',
    site: 'https://www.armac.com.br',
    grupo: 'Serviços',
  },
  {
    ticker: 'MLAS3',
    nome: 'Multilaser (Lasa)',
    emoji: '🖱️',
    setor: 'Eletrônicos',
    frase: 'A marca do mouse, do fone e do carregador baratinho que você acha em qualquer loja.',
    oQueFaz: 'A Multilaser desenvolve e vende eletrônico de consumo acessível: acessório de informática, som, pequeno eletrodoméstico. Ganha com preço competitivo e distribuição ampla no varejo.',
    vocesUsa: 'Aquele cabo, fone ou caixinha de som barata que você comprou já foi Multilaser.',
    dono: 'Ser dono da Multilaser é ter um pedaço do eletrônico popular brasileiro.',
    site: 'https://www.multi.com.br',
    grupo: 'Tecnologia e Telecom',
  },
]

// mapa rápido pra buscar por ticker
export const EMPRESA_POR_TICKER: Record<string, EmpresaBroto> = Object.fromEntries(
  EMPRESAS.map((e) => [e.ticker, e]),
)
